### ISSUE TITLE
เอาเมนูออก

### ISSUE THREAD

**Issue by consult-bcircle** [bcircle/alfresco-pdf-toolkit#1]
เอาเมนูออกตามภาพเลยครับ (ส่วนที่แสดงเมนูหน้าเมื่อ Preview File อันนี้ยังคงมีเหมือนเดิม)

![image](https://cloud.githubusercontent.com/assets/19705462/18075337/1aee75c8-6e9e-11e6-925f-dae8f80b78a5.png)

**Comment by phuchiss** [comment]
https://github.com/bcircle/alfresco-pdf-toolkit/releases/tag/1.4.3
