### ISSUE TITLE
Encrypt PDF Document ที่ช่อง 7 ใช้งานแล้ว failed

### ISSUE THREAD

**Issue by consult-bcircle** [bcircle/alfresco-pdf-toolkit#5]
ฟังก์ชั่น Encrypt PDF Document ที่ช่อง 7 ใช้งานแล้ว failed
![image](https://cloud.githubusercontent.com/assets/19705462/23588704/ef56e622-01f3-11e7-8660-a0a4f9416cf8.png)

**Comment by consult-bcircle** [comment]
......

**Comment by wk-j** [comment]
โปรเจคนี้เป็น Opensouce ครับ ไม่ควรนำ Password มาวางครับ
